server:
  # 设置服务启动端口
  port: 8888

spring:
  profiles:
    active: prod # 选择 开发环境/预设配置
  # MailProperties 邮箱设置
  mail:
    host: smtp.163.com   # 声明邮箱域名
    port: 465             # 邮箱端口
    username: 15653674386@163.com    # 邮箱账号
    password: RBNJGWNAHZSMLRTO   # 邮箱授权码
    protocol: smtp       # 协议
    properties:
      mail:
        smtp:
          ssl:
            enable: true     # 发送邮件时采用ssl安全连接

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
---
# 设置dev开发环境
spring:
  profiles: dev # 设置预设名
  # 配置MySql数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 设置驱动程序
    Type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/QanXun_IOT?useSSL=false # 设置数据库
    username: root  # 数据库用户名
    password: 1234  # 数据库密码
  # 配置Redis数据源
  redis:
    host: 127.0.0.1 # 连接地址
    port: 6379 # 连接端口
    jedis:
      pool:
        max-active: 8 # 最大连接数
        max-wait: -1 # 最大阻塞等待时间(-1表示无限制)
        max-idle: 8 # 最大空闲
        min-idle: 0 # 最小空闲
#   开启MybatisPlus数据库操作日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.baomidou.mybatisplus: debug
  config: classpath:logback/dev-logback.xml # 配置LogBack日志框架配文件路径
logPath: "F:/Y_xianlin/java_log"
mybatis:
  config-location: classpath:mybatis-config-dev.xml # 配置Mybatis配置文件路径
  mapper-locations: classpath:mapper/*Dao.xml # 配置Mybatis映射文件路径
---
# 设置prod生产环境
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    Type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.21.0.16:3306/qanxun_iot?useSSL=false
    username: root
    password: wgw147741QWE

  # 配置Redis数据源
  redis:
    host: api.shuxinxin.top # 连接地址
    port: 6379 # 连接端口
    jedis:
      pool:
        max-active: 8 # 最大连接数
        max-wait: -1 # 最大阻塞等待时间(-1表示无限制)
        max-idle: 8 # 最大空闲
        min-idle: 0 # 最小空闲

logging:
  # 配置LogBack日志框架配文件路径
  config: classpath:logback/prod-logback.xml
logPath: "/log"
---
# 设置inside内部环境
spring:
  profiles: inside
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    Type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://bj-cynosdbmysql-grp-o8fpl778.sql.tencentcdb.com:29815/qanxun_iot?useSSL=false
    username: root
    password: wgw147741QWE

  # 配置Redis数据源
  redis:
    host: 192.168.89.10 # 连接地址
    port: 6379 # 连接端口
    jedis:
      pool:
        max-active: 8 # 最大连接数
        max-wait: -1 # 最大阻塞等待时间(-1表示无限制)
        max-idle: 8 # 最大空闲
        min-idle: 0 # 最小空闲
logging:
  # 配置LogBack日志框架配文件路径
  config: classpath:logback/dev-logback.xml
---
# 设置test生产环境
spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    Type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://bj-cynosdbmysql-grp-o8fpl778.sql.tencentcdb.com:29815/qanxun_iot?useSSL=false
    username: root
    password: wgw147741QWE

  # 配置Redis数据源
  redis:
    host: 192.168.89.10 # 连接地址
    port: 6379 # 连接端口
    jedis:
      pool:
        max-active: 8 # 最大连接数
        max-wait: -1 # 最大阻塞等待时间(-1表示无限制)
        max-idle: 8 # 最大空闲
        min-idle: 0 # 最小空闲
logging:
  # 配置LogBack日志框架配文件路径
  config: classpath:logback/dev-logback.xml